const fs = require("fs");
const path = require("path");

const FRONTEND_DIR = path.join(__dirname, "../lib/contracts");
const DEPLOYMENTS_ROOT = path.join(__dirname, "deployments");

const NETWORK_PRIORITY = ["celo", "hardhat"];
const CONTRACTS_TO_SYNC = ["EmploymentContract"];

if (!fs.existsSync(FRONTEND_DIR)) {
  fs.mkdirSync(FRONTEND_DIR, { recursive: true });
}

function sync() {
  console.log("--- Syncing EmploymentContract artifacts ---");

  if (!fs.existsSync(DEPLOYMENTS_ROOT)) {
    console.warn("No deployments directory found at", DEPLOYMENTS_ROOT);
    console.warn("Deploy first, then re-run: bun run sync (or npm run sync)");
    process.exit(0);
  }

  let multiAddresses = {};
  const abis = {};
  const syncedNetworks = [];

  const existingAddressesFile = path.join(FRONTEND_DIR, "addresses.json");
  if (fs.existsSync(existingAddressesFile)) {
    try {
      multiAddresses = JSON.parse(fs.readFileSync(existingAddressesFile, "utf8"));
    } catch {
      console.warn("Could not parse existing addresses.json");
    }
  }

  for (const net of NETWORK_PRIORITY) {
    const networkDir = path.join(DEPLOYMENTS_ROOT, net);
    if (!fs.existsSync(networkDir)) {
      console.warn(`  Skipping ${net}: directory not found.`);
      continue;
    }

    const chainIdFile = path.join(networkDir, ".chainId");
    if (!fs.existsSync(chainIdFile)) {
      console.warn(`  Skipping ${net}: .chainId not found.`);
      continue;
    }

    const chainId = fs.readFileSync(chainIdFile, "utf8").trim();
    syncedNetworks.push({ name: net, chainId });

    for (const name of CONTRACTS_TO_SYNC) {
      const filePath = path.join(networkDir, `${name}.json`);
      if (!fs.existsSync(filePath)) continue;

      const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
      if (!multiAddresses[name]) multiAddresses[name] = {};
      multiAddresses[name][chainId] = data.address;

      if (!abis[name]) {
        abis[name] = data.abi;
        console.log(`  Extracted ABI for ${name} from ${net}`);
      }

      console.log(`  [${net}] ${name} @ ${data.address}`);
    }
  }

  fs.writeFileSync(
    path.join(FRONTEND_DIR, "addresses.json"),
    JSON.stringify(multiAddresses, null, 2),
  );
  fs.writeFileSync(
    path.join(FRONTEND_DIR, "abis.json"),
    JSON.stringify(abis, null, 2),
  );

  const primaryChain =
    syncedNetworks.find((n) => n.name === "celo")?.chainId ??
    syncedNetworks[0]?.chainId ??
    "42220";

  const tsContent = `/**
 * Generated by smartContracts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: ${syncedNetworks.map((n) => `${n.name} (${n.chainId})`).join(", ") || "none yet"}
 */

import addresses from "./addresses.json";
import abis from "./abis.json";

export type Address = \`0x\${string}\`;

export const CONTRACTS = {
  EmploymentContract: {
    address: (addresses as any)?.EmploymentContract?.[${JSON.stringify(primaryChain)}] as Address | undefined,
    addresses: (addresses as any)?.EmploymentContract ?? {},
    abi: (abis as any)?.EmploymentContract ?? [],
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
`;

  fs.writeFileSync(path.join(FRONTEND_DIR, "index.ts"), tsContent);
  console.log("\n--- Sync complete ---");
  console.log("Wrote lib/contracts/{addresses,abis,index}.{json,ts}");
}

sync();
