const fs = require("fs");
const path = require("path");

const FRONTEND_DIR = path.join(__dirname, "../ui/lib/contracts");
const DEPLOYMENTS_ROOT = path.join(__dirname, "deployments");
const ARTIFACTS_ROOT = path.join(__dirname, "artifacts", "contracts");

const NETWORK_PRIORITY = ["celo"];
/** Deployed contracts synced into CONTRACTS (address + ABI). */
const CONTRACTS_TO_SYNC = ["EmploymentManager", "SentryWalletFactory", "RewardFactory"];
/**
 * Implementation ABIs without a single deployment address (created per key by factories).
 * Synced from Hardhat artifacts into abis.json and exported from index.ts.
 */
const IMPLEMENTATION_ABIS = [
  { name: "RewardAccount", artifact: "RewardAccount.sol/RewardAccount.json" },
];

if (!fs.existsSync(FRONTEND_DIR)) {
  fs.mkdirSync(FRONTEND_DIR, { recursive: true });
}

function loadArtifactAbi(relativePath) {
  const filePath = path.join(ARTIFACTS_ROOT, relativePath);
  if (!fs.existsSync(filePath)) {
    console.warn(`  Skipping artifact ABI: ${relativePath} not found (compile first).`);
    return null;
  }
  const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
  return Array.isArray(data.abi) ? data.abi : null;
}

function sync() {
  console.log("--- Syncing contract artifacts ---");

  if (!fs.existsSync(DEPLOYMENTS_ROOT)) {
    console.warn("No deployments directory found at", DEPLOYMENTS_ROOT);
    console.warn("Deploy first, then re-run: bun run sync (or npm run sync)");
    process.exit(0);
  }

  let multiAddresses = {};
  const abis = {};
  const syncedNetworks = [];

  const existingAddressesFile = path.join(FRONTEND_DIR, "addresses.json");
  if (fs.existsSync(existingAddressesFile)) {
    try {
      multiAddresses = JSON.parse(fs.readFileSync(existingAddressesFile, "utf8"));
    } catch {
      console.warn("Could not parse existing addresses.json");
    }
  }

  // Preserve previously synced ABIs (e.g. RewardAccount) if artifacts are missing locally.
  const existingAbisFile = path.join(FRONTEND_DIR, "abis.json");
  if (fs.existsSync(existingAbisFile)) {
    try {
      Object.assign(abis, JSON.parse(fs.readFileSync(existingAbisFile, "utf8")));
    } catch {
      console.warn("Could not parse existing abis.json");
    }
  }

  for (const net of NETWORK_PRIORITY) {
    const networkDir = path.join(DEPLOYMENTS_ROOT, net);
    if (!fs.existsSync(networkDir)) {
      console.warn(`  Skipping ${net}: directory not found.`);
      continue;
    }

    const chainIdFile = path.join(networkDir, ".chainId");
    if (!fs.existsSync(chainIdFile)) {
      console.warn(`  Skipping ${net}: .chainId not found.`);
      continue;
    }

    const chainId = fs.readFileSync(chainIdFile, "utf8").trim();
    syncedNetworks.push({ name: net, chainId });

    for (const name of CONTRACTS_TO_SYNC) {
      const filePath = path.join(networkDir, `${name}.json`);
      if (!fs.existsSync(filePath)) continue;

      const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
      if (!multiAddresses[name]) multiAddresses[name] = {};
      multiAddresses[name][chainId] = data.address;

      // Prefer Hardhat artifact ABI (tracks local source) over deployment snapshot.
      const artifactAbi = loadArtifactAbi(`${name}.sol/${name}.json`);
      if (artifactAbi) {
        abis[name] = artifactAbi;
        console.log(`  Extracted ABI for ${name} from artifacts (address from ${net})`);
      } else if (data.abi) {
        abis[name] = data.abi;
        console.log(`  Extracted ABI for ${name} from ${net} deployment`);
      }

      console.log(`  [${net}] ${name} @ ${data.address}`);
    }
  }

  for (const { name, artifact } of IMPLEMENTATION_ABIS) {
    const abi = loadArtifactAbi(artifact);
    if (abi) {
      abis[name] = abi;
      console.log(`  Extracted implementation ABI for ${name} from artifacts`);
    }
  }

  fs.writeFileSync(
    path.join(FRONTEND_DIR, "addresses.json"),
    JSON.stringify(multiAddresses, null, 2),
  );
  fs.writeFileSync(
    path.join(FRONTEND_DIR, "abis.json"),
    JSON.stringify(abis, null, 2),
  );

  const primaryChain =
    syncedNetworks.find((n) => n.name === "celo")?.chainId ??
    syncedNetworks[0]?.chainId ??
    "42220";

  const contractEntries = CONTRACTS_TO_SYNC.map((name) => {
    return `  ${name}: {
    address: addresses.${name}[${JSON.stringify(primaryChain)}] as Address,
    abi: abis.${name},
  }`;
  }).join(",\n");

  const implExports = IMPLEMENTATION_ABIS.map(
    ({ name }) =>
      `/** ${name} ABI (synced from artifacts; instances are created by factories). */\nexport const ${name
        .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
        .toUpperCase()}_ABI = abis.${name};`,
  ).join("\n");

  const tsContent = `/**
 * Generated by smartContracts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: ${syncedNetworks.map((n) => `${n.name} (${n.chainId})`).join(", ") || "none yet"}
 */

import addresses from "./addresses.json";
import abis from "./abis.json";

export type Address = \`0x\${string}\`;

export const CONTRACTS = {
${contractEntries},
} as const;

export type ContractName = keyof typeof CONTRACTS;

${implExports}
`;

  fs.writeFileSync(path.join(FRONTEND_DIR, "index.ts"), tsContent);
  console.log("\n--- Sync complete ---");
  console.log("Wrote lib/contracts/{addresses,abis,index}.{json,ts}");
  console.log(
    "Note: RewardAccount DB rows auto-heal on next Wallets/overview load (reconcile via factory.accountOfKey).",
  );
}

sync();
