/**
 * Generated by smartContracts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: celo (42220)
 */

import addresses from "./addresses.json";
import abis from "./abis.json";

export type Address = `0x${string}`;

export const CONTRACTS = {
  EmploymentManager: {
    address: addresses.EmploymentManager["42220"] as Address,
    abi: abis.EmploymentManager,
  },
  SentryWalletFactory: {
    address: addresses.SentryWalletFactory["42220"] as Address,
    abi: abis.SentryWalletFactory,
  },
  RewardFactory: {
    address: addresses.RewardFactory["42220"] as Address,
    abi: abis.RewardFactory,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;

/** RewardAccount ABI (synced from artifacts; instances are created by factories). */
export const REWARD_ACCOUNT_ABI = abis.RewardAccount;
