/**
 * Generated by smartContracts/sync-data.js — DO NOT EDIT MANUALLY.
 * Networks: celo (42220)
 * RewardFactory address is placeholder until deploy (env REWARD_FACTORY_ADDRESS overrides).
 */

import addresses from "./addresses.json";
import abis from "./abis.json";

export type Address = `0x${string}`;

export const CONTRACTS = {
  EmploymentManager: {
    address: addresses.EmploymentManager["42220"] as Address,
    abi: abis.EmploymentManager,
  },
  SentryWalletFactory: {
    address: addresses.SentryWalletFactory["42220"] as Address,
    abi: abis.SentryWalletFactory,
  },
  RewardFactory: {
    address: (addresses.RewardFactory?.["42220"] ??
      "0x0000000000000000000000000000000000000000") as Address,
    abi: abis.RewardFactory,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;

/** Minimal RewardAccount ABI for operator payouts / lifecycle reads. */
export const REWARD_ACCOUNT_ABI = abis.RewardAccount;
